[package]
org = "ankit_singh1"
name = "data_service_in_ballerina"
version = "0.1.0"
distribution = "2201.1.1"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"
